services:
  - type: web
    name: zen-gpt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_PAGE_ID
        sync: false
